package model.paint.strategy;

import java.awt.geom.AffineTransform;

import model.paint.ShapePaintStrategy;
import model.paint.shape.Fish1PolygonFactory;

/**
 * Paint strategy that paints a fish-shaped Polygon generated by a Fish1PolyfonFactory.
 * @author kq2
 *
 */
public class Fish1PaintStrategy extends ShapePaintStrategy {
	
	/**
	 * No-parameter constructor that instantiates the AffineTransform for internal use.
	 */
	public Fish1PaintStrategy() {
		this(new AffineTransform());
	}
	
	/**
	 * Constructor that takes an external AffineTransform
	 * @param at The AffineTransform to use for internal use.
	 */
	public Fish1PaintStrategy(AffineTransform at) {
		super(at, Fish1PolygonFactory.Singleton.makeShape(0.0, 0.0, 1.0, 0.5));
	}
	
}
